name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: SiDevesh/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        BASE_BRANCH: master
        FOLDER: website/build
        BASE_DIRECTORY: website
        BUILD_SCRIPT: npm install && npm run build
